name: Website Building Test

on:
    pull_request:
        branches:
            - dev
        paths:
            - 'website/**'
            - '!website/**/*.md'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  # SEE: https://github.com/lerna/lerna/issues/2542
                  fetch-depth: '0'

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 21

            - name: Install dependencies
              run: yarn site:build
