name: Playground Test

on:
    pull_request:
        branches:
            - dev
        paths:
            - 'playground/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  # SEE: https://github.com/lerna/lerna/issues/2542
                  fetch-depth: '0'

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 21

            - name: Cache Restore devDependencies
              id: cache-restore-dev-depends
              uses: actions/cache/restore@v4
              with:
                  path: '**/node_modules'
                  key: dev-depends-ubuntu-latest-node21-${{ hashFiles('yarn.lock') }}

            - name: Playground Building Test
              run: yarn pg:build

    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  # SEE: https://github.com/lerna/lerna/issues/2542
                  fetch-depth: '0'

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 21

            - name: Cache Restore devDependencies
              id: cache-restore-dev-depends
              uses: actions/cache/restore@v4
              with:
                  path: '**/node_modules'
                  key: dev-depends-ubuntu-latest-node21-${{ hashFiles('yarn.lock') }}

            - name: Install root dependencies
              run: yarn install --frozen-lockfile

            - name: Playground Lint
              run: yarn pg:lint
